name = "UnfoldStats"
uuid = "96fd419a-8306-4ce8-ba5b-cd907cb7647c"
authors = ["Judith Schepers", "Benedikt V. Ehinger"]
version = "1.0.0-DEV"

[deps]
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
ClusterDepth = "c8d8bbfa-f476-4995-adff-2987f04015d1"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
MixedModelsPermutations = "647c4018-d7ef-4d03-a0cc-8889a722319e"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Unfold = "181c99d8-e21b-4ff3-b70b-c233eddec679"

[weakdeps]
ClusterDepth = "c8d8bbfa-f476-4995-adff-2987f04015d1"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
MixedModelsPermutations = "647c4018-d7ef-4d03-a0cc-8889a722319e"

[extensions]
UnfoldStatsMixedModelsExt = ["MixedModels"]
UnfoldStatsMixedModelsPermutationsExt = ["ClusterDepth", "MixedModelsPermutations"]

[compat]
BSplineKit = "0.16,0.17"
ClusterDepth = "0.2"
MixedModels = "4"
MixedModelsPermutations = "0.2"
StatsModels = "0.7"
Unfold = "0.6,0.7"
julia = "1.9,1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
