name = "UnfoldStats"
uuid = "96fd419a-8306-4ce8-ba5b-cd907cb7647c"
authors = ["Judith Schepers", "Benedikt V. Ehinger"]
version = "0.2.0"

[deps]
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Unfold = "181c99d8-e21b-4ff3-b70b-c233eddec679"

[weakdeps]
ClusterDepth = "c8d8bbfa-f476-4995-adff-2987f04015d1"
MixedModelsPermutations = "647c4018-d7ef-4d03-a0cc-8889a722319e"
UnfoldMixedModels = "019ae9e0-8363-565c-86e5-97a5a2fe84f4"

[extensions]
UnfoldStatsMixedModelsExt = ["UnfoldMixedModels"]
UnfoldStatsMixedModelsPermutationsExt = ["UnfoldMixedModels", "ClusterDepth", "MixedModelsPermutations"]

[compat]
BSplineKit = "0.16,0.17,0.18"
ClusterDepth = "0.2"
Logging = "1"
MixedModelsPermutations = "0.2"
Random = "1"
StatsAPI = "1"
StatsModels = "0.7"
Unfold = "0.8"
UnfoldMixedModels = "0.1"
julia = "1.10,1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
